coreruleset/modsecurity-docker

Dockerfile
Note the SIZE columns below.
```
Before:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
modsec              latest              5821e8dd49ea        3 minutes ago       821.6 MB
docker.io/fedora    25                  15895ef0b3b2        11 weeks ago        230.9 MB
After dnf clean:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
modsec              latest              80249f84011a        10 seconds ago      653.3 MB
docker.io/fedora    25                  15895ef0b3b2        11 weeks ago        230.9 MB
After make clean:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
modsec              latest              e3c593033360        4 minutes ago       634.6 MB
docker.io/fedora    25 …
```
=> Slimdown size of image

Dockerfile
Update ModSecurity from 2.9.2 to current version 2.9.3 for branch v2/ubuntu-apache.
Please also rebuild Docker image tag 2.9-apache-ubuntu.
=> Update ModSecurity to 2.9.3 for ubuntu-apache image

Dockerfile
Add  wget  unicode.mapping   to  fix  nginx  start error  
Error Detail in   container boot 
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsecurity.d/modsecurity.conf. Line: 236. Column: 17. Failed to locate the unicode map file from: unicode.mapping Looking at: 'unicode.mapping', 'unicode.mapping', '/etc/nginx/modsecurity.d/unicode.mapping', '/etc/nginx/modsecurity.d/unicode.mapping'.  in /etc/nginx/nginx.conf:39
=> Add  wget  unicode.mapping   to  fix  nginx  start error

Dockerfile, httpd-logging-before-modsec.conf
Add extended log format access.log.
I will also provide a PR for the Core Rule Set docker container.
There, the timeout variables will be filled.
=> Add extended access.log

v2-apache/Dockerfile, v3-nginx/Dockerfile
Renaming a file seems irrelevant and unneeded. These changes, though, correct the mental model the word "include" is meant to convey:
* In the context of the web proxy, Apache and Nginx, we mean to include configuration files from ModSecurity.
* In the context of ModSecurity that file is meant as the entrance point to set up the ModSecurity engine when included by the web proxy.
**Related changes:** https://github.com/CRS-support/modsecurity-crs-docker/pull/7 (downsteam image)
=> Rename include.conf -> setup.conf

README.md, v2-apache/Dockerfile, v2-apache/conf/extra/httpd-vhosts.conf
This adds loading `mod_http2` in apache, and configuring default protocols.
=> feat(http2): adds mod_http2 support for apache

v2-apache/Dockerfile
Fixes a problem with latest `httpd:2.4` based on buster that prevented the build. It was lacking `apr` and `apu` configs.
I've also used the same upstream foreground entrypoint instead of adding a new cmd.
=> fix(build): base image moved apr and apu so we need to install it now

.github/workflows/dockerimage.yml
This PR adds a scheduled build for the Docker images.
If we also want to work with tagging the Git repo, we could also add it like I did in https://github.com/coreruleset/modsecurity-crs-docker/pull/24.
=> Add scheduled Docker build to GitHub Action

.github/workflows/dockerimage.yml, .github/workflows/verifyimage.yml, README.md, docker-compose.yml, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine, v3-nginx/docker-entrypoint.sh, version.sh
- Adds Alpine Linux based images.
- `docker-entrypoint.sh` was changed to make it POSIX compliant, so we don't need to install bash shell in Alpine
- Still no build using GHA, will add that in next commits.
=> feat(alpine): add alpine images

v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Last alpine merge broke the ARG build, this one fixes that.
=> fix(ci): fix ARG in dockerfile

README.md, src/etc/modsecurity.d/modsecurity-override.conf
These two should be in the CRS container, not base. Otherwise they get duplicated (they are already set in the crs-setup.conf file).
=> fix(conf): move default actions to crs container instead of base

README.md, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine
Upgrades apache v2 to latest 2.9.4.
=> feat(modsec): upgrade to apache module to v2.9.4

.github/workflows/verifyimage.yml
Basically at least to linux/amd64 to prevent containers not starting or config problems.
=> feat(ci): add verify 

v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile
While both images create and change users to www-data (see upstream build), the `user` in default configuration is the one changed in this PR.
=> Fix uids tmp

v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
- Fixes CVE by updating modsecurity
- Moves arguments to top of Dockerfile, so they are listed once
- Uses set -eux everywhere
=> fix(cve): update modsecurity version

README.md, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine
- Fixes variable usage for `SERVER_ADMIN`
- Documents `SERVER_NAME`
=> fix(apache): SERVER_ADMIN should be used as variable

README.md, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v2-apache/conf/extra/httpd-modsecurity.conf
- adds APACHE_LOGFORMAT variable (default "combined")
- fixes duplicated logging directives from upstream and v2-apache/conf/extra/httpd-modsecurity.conf file
Fixes #125.
=> fix(apache): substitute accesslog from upstream

v3-nginx/templates/conf.d/logging.conf.template
Since we use the real_ip module we also need to use the correct variable
to log the remote addr.
Fixes #129
=> fix: use `$realip_remote_addr` in nginx log format

.github/workflows/dockerimage.yml, .github/workflows/verifyimage.yml, README.md, docker-bake.hcl, v3-nginx/Dockerfile
- tags are based on build date using YYYYMMDDHHMM
- main label does not change, only specific ones
- remove cron build to use dispatched builds or merges only
=> feat(ci): use unique tags when pushing to hub

v2-apache/conf/extra/httpd-modsecurity.conf, v3-nginx/templates/conf.d/logging.conf.template
- The `perflogjson` format did not exist and the `PERFLOG` environment variable had no effect because `write_perflog` was never set.
- Add comments about predefined log formats
Fixes #128
=> bugfix: clean up log formats

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
On debian arm64 path is /usr/lib/aarch64-linux-gnu, and looks like the autoconf script is not finding libraries there.
=> fix(pcre2): add prefix path for additional archs

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
The previous attempt using sed still failed on some architectures.
To fix the problem I've sent a PR for upstream modsecurity build process. While it is not merged, we add it here to the build.
- add the patch from PR 2813
- enable silent build (saves a ton of scrolling when building)
- just clone recursively instead of doing it in two steps
- strip binaries also in alpine
=> fix(pcre2): apply patch from upstream modsec repo

.github/workflows/verifyimage.yml, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
- packages are already available in major distributions
- remove compilation steps for ssdeep and variables
- remove libfuzzy variables
Fixes #142.
=> chore: do not compile existing packages

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
- this trick makes both ssdeep and pcre2 be found in other architectures
- we need `AC_CANONICAL_HOST` earlier in the `configure.ac` file to use its defined the variable `$host_cpu`
=> fix(nginx): use host cpu instead of fixed archs

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Turns out i386 is detected by `uname -m` as x86_64, therefore it still fails to find libraries in that arch. Doing the same change but on x86_64 made both work, and also arm builds.
=> fix(nginx): i386 is detected as x86_64 in build

.github/workflows/verifyimage.yml, README.md, src/bin/healthcheck, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Adds health check to the `/healtz` endpoint configured in all containers.
Fixes #136.
Note: I did try adding variables to the different times, but docker doesn't like it. :( My idea was to add 4 new variables `HEALTHCHECK_`, but looks like we can't.
```
❯ docker-compose build apache-waf
[+] Building 0.1s (2/2) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                                             0.0s
=> => transferring dockerfile: 9.17kB                                                                                                                                                           0.0s
=> [internal] load …
```
=> feat(health): add health check
