Dockerfile
Re-introducing cleanup commands to keep image small.
=> Clean dnf cache and build leftovers.

CONTRIBUTORS.md, Dockerfile
=> Add ssl support to Nginx

Dockerfile
This adds support for the nginx SSL module
=> added openssl and parameter for building nginx with ssl module

Dockerfile
Add environment variables to httpd.conf to configure them during `docker run` instead of setting them during `docker build`.
=> Add environment variables instead of build arguments

Dockerfile, httpd-logging-before-modsec.conf
Set SETTLS and SETPROXY to default value true.
=> Set SETTLS and SETPROXY to true as default

.github/workflows/dockerimage.yml, v3-nginx/Dockerfile
Also fixed some hadolint warnings in Dockerfile
=> Update nginx connecto to 3.0.4

.github/workflows/dockerimage.yml, README.md
* Update README with current ModSecurity version (forgotten in PR #36 review)
* Login only after image build in pipeline
=> Update README with current ModSecurity version image tag

.dependabot/config.yml
=> feat(ci): add dependabot

README.md
=> docs: update github link after migration

.github/workflows/dockerimage.yml
This should fix the cron build on each Monday.
@franbuehler Can you review?
=> fix(ci): push all tags on images

v3-nginx/Dockerfile
Fixes #65.
Can you take a look @franbuehler ?
=> fix(nginx): update to version 1.20.1

README.md, src/etc/modsecurity.d/modsecurity-override.conf, v2-apache/Dockerfile, v3-nginx/Dockerfile
=> feat(vars): add variable for SecResponseBodyMimeType

README.md, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
=> feat(core): update v3 to 3.0.5

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Fixes #92 by making nginx images half the size.
=> feat(nginx): shrink size by stripping and copying only dynamic libs

README.md
=> docs: update readme with pointers to modsecurity directives

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Testing if forcing geoip solves dependency in arm64.
=> fix(ci): add geoip specifically

README.md, docker-compose.yml
Update documentation on beaking changes for nginx config.
=> docs: update nginx config adding breaking changes

README.md, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
- fix env var order
- add missing env vars
- fix some whitespace and indentation differences
- remove unnecessary copy operations
=> chore: clean up differences between Dockerfiles

README.md, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Reverts coreruleset/modsecurity-docker#121
=> Revert "feat(nginx): update to 1.22.0 with support for PCRE2"

README.md, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
Let's go again. This applies #121 again.
=> feat(nginx): update to 1.22.0 with support for PCRE2

.github/workflows/dispatcher.yml, .github/workflows/verifyimage.yml, README.md, v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
- this is another try at getting pcre2 in nginx containers.
Fixes #120.
=> feat(nginx): add support for pcre2

.github/workflows/dispatcher.yml
- remove stale dependency from dispatched workflow
=> fix(ci): remove stale dependency

v3-nginx/templates/includes/proxy_backend.conf.template
=> fix(nginx): corrects upgrade header variable name

v3-nginx/Dockerfile, v3-nginx/Dockerfile-alpine
This one will work for all the architectures now.
=> fix(ci): use gcc -multiarch to get proper arch

README.md, v2-apache/Dockerfile, v2-apache/Dockerfile-alpine, v2-apache/conf/extra/httpd-vhosts.conf
This variable helps to solve issue https://github.com/coreruleset/modsecurity-crs-docker/issues/94.
=> feat(apache): add PROXY_ERROR_OVERRIDE variable
